use_frameworks!

target 'SwiftyInstagram_Example' do
  pod 'SwiftyInstagram', :path => '../'

  target 'SwiftyInstagram_Tests' do
    inherit! :search_paths
    pod 'SwiftyInstagram', :path => '../'
    pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-3.0'
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :commit => 'db706fc'
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
  end
end
