use_frameworks!

target 'SwiftyInstagram_Example' do
  pod 'SwiftyInstagram', :path => '../'

  target 'SwiftyInstagram_Tests' do
    inherit! :search_paths
    pod 'SwiftyInstagram', :path => '../'
    pod 'Quick', '~> 0.9.1'
    pod 'Nimble', '3.2.0'
    pod 'OHHTTPStubs', '~> 5.1.0'
  end
end
