use_frameworks!

target 'SwiftyInstagram_Example' do
  pod 'SwiftyInstagram', :path => '../'

  target 'SwiftyInstagram_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
