# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
#- gem install cocoapods # Since Travis is not always on latest version
#- pod install --project-directory=Example
script:
- gem install cocoapods
- cd Example ; pod install ; cd ..
- set -o pipefail && xcodebuild test -workspace Example/SwiftyInstagram.xcworkspace -scheme SwiftyInstagram-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
